#!/bin/bash

monitor-sensor | while read -r line; do
    if echo "$line" | grep -q 'orientation changed: bottom-up'; then
        # Tabletmodus — uitschakelen
        xinput disable "AT Translated Set 2 keyboard"
        xinput disable "ELAN Touchpad"
    elif echo "$line" | grep -q 'orientation changed: normal'; then
        # Laptopmodus — inschakelen
        xinput enable "AT Translated Set 2 keyboard"
        xinput enable "ELAN Touchpad"
    fi
done
